// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3j_RM2UBEgFC1DY_o-QbuJY7z58OPBY',
    appId: '1:508322250344:web:09ceed6a3835e4b2e305dd',
    messagingSenderId: '508322250344',
    projectId: 'appdevfinalproject-7954d',
    authDomain: 'appdevfinalproject-7954d.firebaseapp.com',
    storageBucket: 'appdevfinalproject-7954d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4QDVbX6Z4zc_sD6NAwEY5Km7zRHG4xf8',
    appId: '1:508322250344:android:8be2881179502bf7e305dd',
    messagingSenderId: '508322250344',
    projectId: 'appdevfinalproject-7954d',
    storageBucket: 'appdevfinalproject-7954d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUR1ALka1tuLS8-E9xRHwV80vtnwlMFQE',
    appId: '1:508322250344:ios:a8f60491f6e376d3e305dd',
    messagingSenderId: '508322250344',
    projectId: 'appdevfinalproject-7954d',
    storageBucket: 'appdevfinalproject-7954d.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUR1ALka1tuLS8-E9xRHwV80vtnwlMFQE',
    appId: '1:508322250344:ios:a8f60491f6e376d3e305dd',
    messagingSenderId: '508322250344',
    projectId: 'appdevfinalproject-7954d',
    storageBucket: 'appdevfinalproject-7954d.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA3j_RM2UBEgFC1DY_o-QbuJY7z58OPBY',
    appId: '1:508322250344:web:55b149cdfd8226a4e305dd',
    messagingSenderId: '508322250344',
    projectId: 'appdevfinalproject-7954d',
    authDomain: 'appdevfinalproject-7954d.firebaseapp.com',
    storageBucket: 'appdevfinalproject-7954d.appspot.com',
  );
}
